---
name: Build project
on:
  push:
    branches:
      - master
    paths:
      - .github/**
      - src/**
      - build.gradle
      - gradle.properties
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"
          cache: "gradle"

      - name: Validate
        uses: pre-commit/action@v3.0.0

      - name: Install playwright
        run: npx playwright install-deps

      - name: Build and Test
        run: ./gradlew clean test
        env:
          PAPA_JOHNS_LOGIN: ${{ secrets.PAPA_JOHNS_LOGIN }}
          PAPA_JOHNS_PASSWORD: ${{ secrets.PAPA_JOHNS_PASSWORD }}
          HEADLESS_MODE: true
          SLOW_MODE: false

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: results
          path: build/allure-results/*
          retention-days: 1

  publish-allure:
    name: Publish allure report
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: results
          path: build/allure-results/

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
