---
name: Build project
on:
  push:
    branches:
      - master
    paths:
      - .github/**
      - src/**
      - build.gradle
      - gradle.properties
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"
          cache: "gradle"

      - name: Validate
        uses: pre-commit/action@v3.0.0

      - name: Install playwright
        run: npx playwright install-deps

      - name: Build and Test
        run: ./gradlew clean test
        env:
          PAPA_JOHNS_LOGIN: ${{ secrets.PAPA_JOHNS_LOGIN }}
          PAPA_JOHNS_PASSWORD: ${{ secrets.PAPA_JOHNS_PASSWORD }}
          HEADLESS_MODE: true
          SLOW_MODE: false
